name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: scripts

    steps:
    
    -   name: Checkout
        uses: actions/checkout@v2
        
    -   name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
    -   name: Set up QEMU
        uses: docker/setup-qemu-action@v1
          
    -   name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
          
    -   name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: robocol/interfaz:latest
          platforms: linux/amd64